### ISSUE TITLE
Error - sed - line 127

### ISSUE THREAD

**Issue by wicadmin** [wdouglascampbell/dehydrated_namecheap_dns_api_hook#2]
I am getting this error from line [127](https://github.com/wdouglascampbell/letsencrypt_namecheap_dns_api_hook/blob/master/namecheap_dns_api_hook.sh#L127). Actually, it is line 126 as I am using seansch fork:

```
/data/dehydrated/hooks/namecheap_dns_api_hook.sh: line 127: syntax error near unexpected token `('
/data/dehydrated/hooks/namecheap_dns_api_hook.sh: line 127: `    local SLD=`sed -E 's/(.*\.)*([^.]+)\..*/\2/' <<< "${FIRSTDOMAIN}"`'
```

**Comment by wdouglascampbell** [comment]
Sorry.  Don't always check the email associated with this github repo.  My only guess is this may be caused by my use of the -E parameter.  If your system doesn't support extended regular expressions then that could explain the error.

You try seeing if the following change to the line would work:
```
local SLD=`sed 's/\(.*\.\)*\([^.]\+\)\..*/\2/' <<< "${FIRSTDOMAIN}"`
```

This will not fix all of the cases where sed -E is used but it would at least indicate why you are getting an error.
